import React from 'react';
import '@refinedev/antd/dist/reset.css';
import { Metadata } from 'next';
import { cookies } from 'next/headers';
import MainContainer from '@components/MainContainer';
import '@refinedev/antd/dist/reset.css';

export const metadata: Metadata = {
  title: 'Refine',
  description: 'Generated by create refine app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get('theme');
  const defaultMode = theme?.value === 'dark' ? 'dark' : 'light';

  console.log('Current theme from cookies:', defaultMode);

  return (
    <html lang="en">
      <body>
        <MainContainer defaultMode={defaultMode}>{children}</MainContainer>
      </body>
    </html>
  );
}
