name: CI/CD Pipeline

on:
  push:
    branches:
      - hubt

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hubt-frontend:latest

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker stop hubt-frontend || true
            docker rm hubt-frontend || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/hubt-frontend:latest
            docker images -f "dangling=true" -q | xargs -r docker rmi
            docker run -d --name hubt-frontend --restart unless-stopped -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/hubt-frontend:latest
